"""Write the manuscript's data bindings from paper/exports/*.json: data.tex macros, table row files, and
data_macros.json (the same macros for non-LaTeX readers such as the project page)."""

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
from string import ascii_lowercase

LATEX_DIR = Path(__file__).resolve().parent
EXPORTS_DIR = LATEX_DIR.parent / "exports"
HEADER = "% AUTO-GENERATED by generate_data.py -- do NOT edit by hand."
MIDRULE = "    \\midrule"

# Row order of every per-policy table: the legend order of the results figure (exporter style.POLICY_ORDER).
POLICY_LABELS = {
    "entropy_coarse_to_fine": "EG-C2F",
    "coarse_to_fine": "C2F",
    "full_then_random": "F-IID",
    "random": "R-IID",
    "repeated_full_scene": "RFS",
    "fine_to_coarse": "F2C",
}
POLICY_ORDER = list(POLICY_LABELS)
# The viewpoints follow from model and input, so one evaluation run suffices; tables mark these with a dagger.
DETERMINISTIC_POLICIES = {"entropy_coarse_to_fine", "repeated_full_scene"}

SCENE_PX = 512
ADE_TABLE_GRIDS = (32, 64)
SWEEP_GRIDS = (8, 16, 32, 64)
ADE_TABLE_TIMESTEPS = (0, 1, 2, 3, 4, 9, 16, 20)
IN1K_TABLE_TIMESTEPS = (0, 1, 2, 3, 4, 5, 9, 15, 20)
# (macro, policy, canvas grid, timestep): read by the project page and the talks (site/), not by the paper.
PAGE_POINTS = (
    ("adeCTFTZero", "coarse_to_fine", 32, 0),
    ("adeCTFCSixFourTZero", "coarse_to_fine", 64, 0),
    ("adeCTFCSixFourTTwenty", "coarse_to_fine", 64, 20),
    ("adeECTFCSixFourTTwenty", "entropy_coarse_to_fine", 64, 20),
    ("adeFIIDCSixFourTTwenty", "full_then_random", 64, 20),
    ("adeRIIDCSixFourTTwenty", "random", 64, 20),
    ("adeFTCCSixFourTTwenty", "fine_to_coarse", 64, 20),
)

# The prose cites rows of tab:ablations by letter, so this order is a contract with the manuscript.
ABLATION_ORDER = (
    "dcan256",
    "qkvo-dcan256",
    "qkvo-dcan384",
    "no-reads",
    "rw-stride6",
    "no-dense",
    "no-fiid-1riid",
    "no-fiid-2riid",
    "no-bptt",
    "vit-s",
    "no-vpe",
)
ABLATION_OVERVIEW_LABELS = {
    "baseline": r"CanViT-B (baseline)",
    "dcan256": r"$D_\mathrm{can} = 256$, asymmetric ($n_h = 2$)",
    "qkvo-dcan256": r"$D_\mathrm{can} = 256$, + QKVO ($n_h = 2$)",
    "qkvo-dcan384": r"$D_\mathrm{can} = 384$, + QKVO ($n_h = 3$)",
    "no-reads": r"No canvas reads",
    "rw-stride6": r"RW stride $= 6$ (1R / 1W)",
    "no-dense": r"No dense supervision",
    "no-fiid-1riid": r"No F-IID, $1 \times$ R-IID",
    "no-fiid-2riid": r"No F-IID, $2 \times$ R-IID",
    "no-bptt": r"No BPTT ($K = 1$)",
    "vit-s": r"$D_\mathrm{bb} = 384$ (= ViT-S backbone)",
    "no-vpe": r"No VPE token",
}
ABLATION_DETAIL_LABELS = {
    "baseline": r"CanViT-B (baseline)",
    "dcan256": r"$D_\mathrm{can} = 256$, asymmetric",
    "qkvo-dcan256": r"$D_\mathrm{can} = 256$, + QKVO",
    "qkvo-dcan384": r"$D_\mathrm{can} = 384$, + QKVO",
    "no-reads": r"No canvas reads",
    "rw-stride6": r"RW stride $= 6$",
    "no-dense": r"No dense supervision",
    "no-fiid-1riid": r"No F-IID, $1 \times$ R-IID",
    "no-fiid-2riid": r"No F-IID, $2 \times$ R-IID",
    "no-bptt": r"No BPTT ($K = 1$)",
    "vit-s": r"$D_\mathrm{bb} = 384$ (ViT-S)",
    "no-vpe": r"No VPE token",
}
ABLATION_METRICS = {"scene_cos_norm": "SceneNorm", "cls_cos_norm": "ClsNorm"}

BENCH_MODELS = ("canvit", "dinov3-vitb16", "dinov3-vits16")
DIGIT_WORDS = ("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")


@dataclass
class Outputs:
    macros: dict[str, str] = field(default_factory=dict)
    row_files: dict[str, list[str]] = field(default_factory=dict)

    def macro(self, name: str, value: str) -> None:
        assert name.isalpha(), f"LaTeX macro names are letters only: {name!r}"
        assert name not in self.macros, f"macro {name} defined twice"
        self.macros[name] = value

    def rows(self, filename: str, rows: list[str]) -> None:
        assert filename not in self.row_files, f"{filename} written twice"
        self.row_files[filename] = rows

    def render(self) -> dict[Path, str]:
        definitions = [f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in self.macros.items()]
        return {
            LATEX_DIR / "data.tex": "\n".join([HEADER, "", *definitions]) + "\n",
            LATEX_DIR / "data_macros.json": json.dumps(self.macros, indent=1, sort_keys=True) + "\n",
            **{LATEX_DIR / name: "\n".join([HEADER, *rows]) + "\n" for name, rows in self.row_files.items()},
        }


def load(name: str) -> dict:
    return json.loads((EXPORTS_DIR / name).read_text())


# Rounds the JSON's decimal value half-up. f"{v:.1f}" rounds the binary float instead: 25.15 (stored as
# 25.1499...) becomes 25.1, and an exact tie such as 4.625 goes to the even neighbour, 4.62.
def fixed(v: float, decimals: int) -> str:
    return str(Decimal(str(v)).quantize(Decimal(1).scaleb(-decimals), rounding=ROUND_HALF_UP))


def fmt1(v: float) -> str:
    return fixed(v, 1)


def sci(v: float) -> str:
    mantissa, exponent = f"{v:.1e}".split("e")
    return f"{mantissa} \\times 10^{{{int(exponent)}}}"


def thousands(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def plural(n: int, singular: str) -> str:
    return f"{n} {singular}" if n == 1 else f"{n} {singular}s"


def row(cells: list[str]) -> str:
    return "    " + " & ".join(cells) + " \\\\"


def bold(s: str) -> str:
    return f"\\textbf{{{s}}}"


def policy_label(policy: str) -> str:
    label = POLICY_LABELS[policy]
    return label + "$^\\dagger$" if policy in DETERMINISTIC_POLICIES else label


def by_policy_order(curves: list[dict]) -> list[dict]:
    return sorted(curves, key=lambda c: (POLICY_ORDER.index(c["policy"]), c["canvas_grid"]))


def curve(curves: list[dict], *, policy: str, canvas_grid: int) -> dict:
    [match] = [c for c in curves if c["policy"] == policy and c["canvas_grid"] == canvas_grid]
    return match


def stochastic_n_runs(curves: list[dict]) -> int:
    n_runs = {c["n_runs"] for c in curves if c["policy"] not in DETERMINISTIC_POLICIES}
    assert len(n_runs) == 1, f"stochastic policies disagree on n_runs: {sorted(n_runs)}"
    return n_runs.pop()


def mean_cell(point: dict, *, n_runs: int, decimals: int) -> str:
    mean = fixed(point["mean"] * 100, decimals)
    if n_runs < 2:
        return mean
    half_width = (point["ci_hi"] - point["ci_lo"]) / 2 * 100
    return f"\\makecell{{{mean} \\\\ $\\pm{fixed(half_width, 2)}$}}"


def policy_table_rows(curves: list[dict], *, timesteps: tuple[int, ...], decimals: int, show_canvas: bool) -> list[str]:
    best = {t: max(c["per_timestep"][t]["mean"] for c in curves) for t in timesteps}
    rows = []
    for c in curves:
        cells = [policy_label(c["policy"])]
        if show_canvas:
            cells.append(f"${c['canvas_grid']}^2$")
        for t in timesteps:
            point = c["per_timestep"][t]
            cell = mean_cell(point, n_runs=c["n_runs"], decimals=decimals)
            cells.append(bold(cell) if point["mean"] >= best[t] else cell)  # every tied winner is bold
        rows.append(row(cells))
    return rows


def sweep(out: Outputs, curves: list[dict], *, prefix: str, decimals: int) -> list[str]:
    grids = sorted({c["canvas_grid"] for c in curves})
    policies = [p for p in POLICY_ORDER if any(c["policy"] == p for c in curves)]
    out.macro(f"{prefix}SweepN", str(stochastic_n_runs(curves)))
    out.macro(f"{prefix}SweepHeader", "\\textbf{Policy} & " + " & ".join(bold(f"$c={g}$") for g in grids))
    rows = []
    for policy in policies:
        cells = [policy_label(policy)]
        for g in grids:
            c = curve(curves, policy=policy, canvas_grid=g)
            best_point = max(c["per_timestep"], key=lambda p: p["mean"])
            cells.append(mean_cell(best_point, n_runs=c["n_runs"], decimals=decimals))
        rows.append(row(cells))
    return rows


def ade20k(out: Outputs, ade: dict) -> None:
    claims = ade["claims"]
    # The paper's ADE20K prose uses the 32x32 canvas.
    single_glimpse = claims["single_glimpse_by_grid"]["32"]
    cheapest_beat = claims["cheapest_beat_by_grid"]["32"]
    out.macro("adeBestMiou", fmt1(claims["best_miou_pct"]))
    out.macro("adeSingleGlimpseMiou", fmt1(single_glimpse["miou_pct"]))
    out.macro("adeBestPriorMiou", fmt1(claims["best_prior_miou_pct"]))
    out.macro("adeBestPriorGflops", fmt1(claims["best_prior_gflops"]))
    out.macro("adeCheapestBeatMiou", fmt1(cheapest_beat["first_beat_miou_pct"]))
    out.macro("adeCheapestBeatFlopRatio", str(round(cheapest_beat["flop_ratio"])))

    baselines = {(b["name"], b["num_glimpses"]): b for b in ade["baselines"]}
    out.macro("ameSetrMiou", fmt1(baselines["AME (SETR)", 8]["miou_pct"]))
    out.macro("adaglimpseEightMiou", fmt1(baselines["AdaGlimpse", 8]["miou_pct"]))

    curves = ade["policy_curves"]
    max_t = max(c["n_timesteps"] for c in curves)
    out.macro("adeMaxT", str(max_t))
    out.macro("adeLastT", str(max_t - 1))
    out.macro("bootstrapCiPct", str(round(ade["_provenance"]["ci"] * 100)))

    teacher = min(
        (r for r in ade["probe_table"] if r["model"] == "DINOv3 ViT-B/16" and r["gflops"] > single_glimpse["gflops"]),
        key=lambda r: r["gflops"],
    )
    out.macro("teacherFlopMatchedMiou", fmt1(teacher["miou_pct"]))
    for name, policy, canvas_grid, t in PAGE_POINTS:
        point = curve(curves, policy=policy, canvas_grid=canvas_grid)["per_timestep"][t]
        out.macro(name, fmt1(point["mean"] * 100))

    table_curves = by_policy_order(
        [c for c in curves if c["scene_size"] == SCENE_PX and c["canvas_grid"] in ADE_TABLE_GRIDS]
    )
    out.macro("adePolicyEvalStochN", str(stochastic_n_runs(table_curves)))
    out.rows(
        "ade20k_seg_rows.tex",
        policy_table_rows(table_curves, timesteps=ADE_TABLE_TIMESTEPS, decimals=1, show_canvas=True),
    )

    sweep_curves = [c for c in curves if c["scene_size"] == SCENE_PX and c["canvas_grid"] in SWEEP_GRIDS]
    out.rows("ade20k_canvas_sweep_rows.tex", sweep(out, sweep_curves, prefix="ade", decimals=1))

    impact_curves = [c for c in sweep_curves if c["policy"] == "coarse_to_fine"]
    out.macro("canvasGridImpactGrids", ", ".join(str(g) for g in sorted(c["canvas_grid"] for c in impact_curves)))
    out.macro("canvasGridImpactN", str(stochastic_n_runs(impact_curves)))


def in1k(out: Outputs, frozen: dict, finetuned: dict) -> None:
    for prefix, data in [("inkFrozen", frozen), ("inkFinetuned", finetuned)]:
        out.macro(f"{prefix}Best", fmt1(max(c["best_mean"] for c in data["configs"]) * 100))
    out.macro("inkMaxT", str(max(c["n_timesteps"] for c in frozen["configs"])))

    for prefix, data, filename in [
        ("inkFrozen", frozen, "in1k_clf_frozen_rows.tex"),
        ("inkFinetuned", finetuned, "in1k_clf_finetuned_rows.tex"),
    ]:
        configs = by_policy_order(data["configs"])
        out.macro(f"{prefix}StochN", str(stochastic_n_runs(configs)))
        out.rows(filename, policy_table_rows(configs, timesteps=IN1K_TABLE_TIMESTEPS, decimals=2, show_canvas=False))

    sweep_curves = frozen["configs"] + frozen["canvas_sweep"]
    out.macro("inkSweepHasData", "1" if frozen["canvas_sweep"] else "0")
    out.rows("in1k_canvas_sweep_rows.tex", sweep(out, sweep_curves, prefix="ink", decimals=2))


def in1k_finetune_config(out: Outputs, cfg: dict) -> None:
    out.macro("inkFtOptimizer", cfg["optimizer"])
    out.macro("inkFtLr", sci(cfg["lr"]))
    out.macro("inkFtWeightDecay", sci(cfg["weight_decay"]))
    out.macro("inkFtGradClip", fmt1(cfg["grad_clip"]))
    out.macro("inkFtBatchSize", str(cfg["batch_size"]))
    out.macro("inkFtLabelSmoothing", str(cfg["label_smoothing"]))
    out.macro("inkFtWarmupSteps", thousands(cfg["warmup_steps"]))
    out.macro("inkFtTotalSteps", thousands(cfg["total_steps"]))
    out.macro("inkFtEpochs", str(cfg["epochs"]))
    out.macro("inkFtNGlimpses", str(cfg["n_glimpses"]))
    out.macro("inkFtBpttMode", "full" if cfg["full_bptt"] else "truncated")


def macro_case(slug: str) -> str:  # "no-fiid-1riid" -> "NoFiidOneRiid"
    assert re.fullmatch(r"[a-z0-9-]+", slug), slug
    return "".join(DIGIT_WORDS[int(p)] if p.isdigit() else p.capitalize() for p in re.findall(r"[a-z]+|\d", slug))


def signed_pct(delta: float) -> tuple[str, str]:
    return ("+" if delta > 0 else "-"), fixed(abs(delta) * 100, 1)


def ci_range(point: dict, metric: str) -> str:
    lo, hi = point[f"{metric}_ci_lo"], point[f"{metric}_ci_hi"]
    return f"{fixed(lo * 100, 1)}--{fixed(hi * 100, 1)}" if lo != hi else fixed(point[metric] * 100, 1)


def ablations(out: Outputs, arch: dict, recon: dict) -> None:
    baseline = arch["_meta"]["baseline_slug"]
    assert tuple(s for s in arch["_meta"]["order"] if s != baseline) == ABLATION_ORDER, arch["_meta"]["order"]
    deltas = {slug: v["deltas"] for slug, v in recon["variants"].items()}

    def text_delta(slug: str, metric: str) -> str:
        sign, magnitude = signed_pct(deltas[slug][metric])
        return f"{'+' if sign == '+' else '$-$'}{magnitude}\\%"

    base = arch["variants"][baseline]
    overview = [
        row([ABLATION_OVERVIEW_LABELS[baseline], base["params_str"], base["gflops_str"], "ref", "ref"]),
        MIDRULE,
    ]
    for letter, slug in zip(ascii_lowercase, ABLATION_ORDER):
        variant = arch["variants"][slug]
        overview.append(
            row(
                [
                    f"\\textbf{{{letter}}} {ABLATION_OVERVIEW_LABELS[slug]}",
                    variant["params_str"],
                    variant["gflops_str"],
                    *(text_delta(slug, metric) for metric in ABLATION_METRICS),
                ]
            )
        )
    out.rows("ablation_overview_rows.tex", overview)

    out.macro("ablStepsK", f"{round(arch['_meta']['n_steps'] / 1000)}k")
    provenance = recon["_provenance"]
    num_timesteps = provenance["n_timesteps"]
    out.macro("ablT", str(num_timesteps))
    out.macro("ablTLast", str(num_timesteps - 1))
    out.macro("ablPolicyName", POLICY_LABELS[provenance["policy"]])
    n_runs = {v["n_runs"] for v in recon["variants"].values()}
    assert len(n_runs) == 1, f"ablation variants disagree on n_runs: {sorted(n_runs)}"
    out.macro("ablNRuns", str(n_runs.pop()))

    # Read through \abldelta{Slug}{Metric}, a \csname lookup that renders a missing entry as nothing,
    # so every (variant, metric) cell is defined.
    for slug in ABLATION_ORDER:
        for metric, suffix in ABLATION_METRICS.items():
            sign, magnitude = signed_pct(deltas[slug][metric])
            out.macro(f"abl{macro_case(slug)}{suffix}", f"${sign}{magnitude}\\%$")

    def detail_row(label: str, slug: str) -> str:
        points = recon["variants"][slug]["per_timestep"]
        first, last = points[0], points[num_timesteps - 1]
        return row([label, *(ci_range(p, m) for p in (first, last) for m in ABLATION_METRICS)])

    detail = [detail_row(ABLATION_DETAIL_LABELS[baseline], baseline), MIDRULE]
    for letter, slug in zip(ascii_lowercase, ABLATION_ORDER):
        detail.append(detail_row(f"\\textbf{{{letter}}} {ABLATION_DETAIL_LABELS[slug]}", slug))
    out.rows("ablation_detail_rows.tex", detail)


def latency_bench(out: Outputs, bench: dict) -> None:
    provenance = bench["_provenance"]
    out.macro("benchTimeBudgetS", str(int(provenance["time_budget_s"])))
    out.macro("benchMaxIters", str(provenance["max_iters"]))
    out.macro("benchNPasses", str(provenance["n_passes"]))
    out.macro("benchWarmupItersPhrase", plural(provenance["warmup_iters"], "warmup iteration"))
    out.macro("benchMinItersPhrase", plural(provenance["min_iters"], "iteration"))
    out.macro("benchNPassesPhrase", plural(provenance["n_passes"], "time"))

    def setup(c: dict) -> tuple[str, str, int]:
        return c["device"], c["dtype"], c["num_threads_actual"]

    def setup_label(device: str, dtype: str, threads: int) -> str:
        if device == "cpu":
            return f"CPU, {threads}T"
        return "CUDA, " + ("AMP bf16" if dtype == "amp-bf16" else dtype)

    def ms(v: float) -> str:
        return fixed(v, 2 if v < 10 else 1 if v < 100 else 0)

    configs = {(setup(c), c["scene_px"], c["model"]): c for c in bench["configs"]}
    rows, previous = [], None
    for s, px in dict.fromkeys((setup(c), c["scene_px"]) for c in bench["configs"]):
        if previous is not None and s != previous:
            rows.append(MIDRULE)
        previous = s
        times = [configs[s, px, m]["min_ms"] for m in BENCH_MODELS]
        mems = [configs[s, px, m]["peak_mem_mb"] for m in BENCH_MODELS]  # None on CPU
        cells = [setup_label(*s), f"${px // 16} \\times {px // 16}$"]
        for t, mem in zip(times, mems):
            cells.append(bold(ms(t)) if t == min(times) else ms(t))
            if mem is None:
                cells.append("---")
            else:
                cells.append(bold(fixed(mem, 0)) if mem == min(m for m in mems if m is not None) else fixed(mem, 0))
        rows.append(row(cells))
    out.rows("hw_bench_rows.tex", rows)


def passive_comparison(out: Outputs, ade: dict) -> None:
    def rows_for(models: list[dict]) -> list[str]:
        return [
            row(
                [
                    r["model"],
                    f"{r['input_px']}\\,px",
                    f"${r['output_grid']} \\times {r['output_grid']}$",
                    fmt1(r["gflops"]),
                    fmt1(r["miou_pct"]),
                ]
            )
            for r in sorted(models, key=lambda r: r["gflops"])
        ]

    table = ade["probe_table"]
    out.rows(
        "passive_comparison_rows.tex",
        [
            *rows_for([r for r in table if r["model"] == "DINOv3 ViT-S/16"]),
            MIDRULE,
            *rows_for([r for r in table if r["model"] == "DINOv3 ViT-B/16"]),
            MIDRULE,
            *rows_for([r for r in table if r["model"].startswith("CanViT")]),
        ],
    )


def dinov3_probes(out: Outputs, probes: list[dict]) -> None:
    def accuracy_row(p: dict) -> str:
        reproduced = bold(fixed(p["real_top1"], 2) + "\\%")
        return row(
            [p["model"], f"{fixed(p['official_real_top1'], 1)}\\% / {reproduced}", fixed(p["in1k_top1"], 2) + "\\%"]
        )

    out.rows("dinov3_probe_accuracy.tex", [accuracy_row(p) for p in probes])
    out.rows(
        "dinov3_probe_hparams.tex",
        [
            row(
                [
                    p["model"],
                    p["objective"],
                    str(p["batch_size"]),
                    f"${sci(p['peak_lr'])}$",
                    f"${sci(p['weight_decay'])}$",
                    f"$({fixed(p['beta1'], 2)}, {fixed(p['beta2'], 2)})$",
                    "Yes" if p["use_dinov3_init"] else "No",
                    f"{p['n_train_epochs']}, {p['total_epochs']}",
                ]
            )
            for p in probes
        ],
    )


def flops(out: Outputs, flops_export: dict) -> None:
    canvit = flops_export["canvit"]
    c64 = canvit["c64"]
    out.macro("cSixFourCanvasGrid", str(c64["canvas_grid"]))
    out.macro("cSixFourAsymRwPairGf", fmt1(c64["asym_rw_pair_gf"]))
    out.macro("cSixFourFullRwPairGf", fmt1(c64["full_rw_pair_gf"]))
    out.macro("flopsCvCanvasDim", str(canvit["canvas_dim"]))
    out.macro("flopsCvNLocal", str(canvit["n_local"]))
    out.macro("flopsCvNPatches", str(canvit["n_patches"]))
    out.macro("flopsCvBackboneRegs", str(canvit["backbone_regs"]))
    # Cost of one canvas-side projection relative to the attention it accompanies: D_can / (2 n_local).
    out.macro("projSdpaRatio", fmt1(canvit["canvas_dim"] / (2 * canvit["n_local"])))


def mask_size_method(out: Outputs, iou_vs_obj: dict) -> None:
    lowess, plotting = iou_vs_obj["lowess"], iou_vs_obj["plotting"]
    out.macro("lowessFrac", str(lowess["frac"]))
    out.macro("lowessIt", str(lowess["it"]))
    out.macro("lowessNBoot", thousands(lowess["n_boot"]))
    out.macro("lowessCiPct", str(round(lowess["ci"] * 100)))
    out.macro("lowessTDeltaEarly", str(plotting["t_delta_early"]))
    out.macro("lowessTDeltaLate", str(plotting["t_delta_late"]))


def generate() -> Outputs:
    out = Outputs()
    ade = load("ade20k_seg.json")
    ade20k(out, ade)
    in1k(out, load("in1k_clf_frozen.json"), load("in1k_clf_finetuned.json"))
    in1k_finetune_config(out, load("in1k_finetune_config.json"))
    ablations(out, load("ablation_variants.json"), load("ablation_recon.json"))
    latency_bench(out, load("hw_bench.json"))
    passive_comparison(out, ade)
    dinov3_probes(out, load("dinov3_probe_data.json")["probes"])
    flops(out, load("flops.json"))
    mask_size_method(out, load("ade20k_iou_vs_obj.json"))
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a generated file differs from the exports")
    args = parser.parse_args()

    expected = generate().render()
    if args.check:
        stale = [p.name for p, text in expected.items() if not p.exists() or p.read_text() != text]
        if stale:
            sys.exit(f"Stale; run `just -f latex/justfile data`: {', '.join(stale)}")
        print(f"{len(expected)} generated files are up to date.")
        return
    for path, text in expected.items():
        path.write_text(text)
    print(f"Wrote {len(expected)} files to {LATEX_DIR}.")


if __name__ == "__main__":
    main()
